config/routes.rb
Hlgsatracker::Application.routes.draw do
  get "sessions/new"
  root to: "sessions#new"
  get "users/new"
  get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  get 'welcome/index'
  get 'welcome/help'
  resources :members
  resources :events
  resources :users
match 'track' => "events#track"
match 'attend' => "events#attend"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :location, :time, :title, :invite, :tracked
  has_and_belongs_to_many:members
  validates :title, presence: true,
                    length: { minimum: 2 }
  validates :date, presence: true
  validates :time, presence: true
  validates :location, presence: true
  validates :description, presence: true

end

app/models/member.rb
class Member < ActiveRecord::Base
attr_accessible :department, :designation, :email, :first_name, :last_name, :paying, :status, :uin
  has_and_belongs_to_many:events
  validates :uin, presence: true,
                    length: { is: 4 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :department, presence: true,
                    length: { is: 4 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  def authenticate
    redirect_to(login) if $user.nil?
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_filter :authenticate
  def new
    @event = Event.new 
  end
 
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    #@event.tracked = false
    if event_params[:invite] == "all"
    @members = Member.all
    @event.members << @members
    elsif event_params[:invite] == "officers"
    @members = Member.where(designation: 'officer')
    @event.members << @members
    end 

    if @event.save
			if @event.members.any?
    		@mail_list = @event.members.map(&:email)
    		EventMailer.event_invite(@mail_list, @event).deliver!
    		flash[:notice] = "Event successfully created"
    	else
    		flash[:notice] = "Event successfully created. No members invited"
    	end
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
			@event = Event.find(params[:id])
			if event_params[:invite] == "all"
			 @event.members.destroy_all
			 @members = Member.all
			 @event.members << @members				#if all members are invited, insert all members in the join table
			elsif event_params[:invite] == "officers"
			 @event.members.destroy_all
			 @members = Member.where(designation: 'officer')
			 @event.members << @members				#if only officers are invited, insert members with officer designation only in the join table
			end 

    if @event.update_attributes(event_params)
      if @event.members.any?
      	@mail_list = @event.members.map(&:email)
      	EventMailer.event_update(@mail_list, @event).deliver!
      	flash[:notice] = "Event successfully updated"
      else
      	flash[:notice] = "Event successfully updated. No members invited"
      end
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def track
    @event = Event.find(params[:id])
  end

  def attend
    @event = Event.find(params[:event_id].to_s)
    @event.members.destroy_all			#after loading all invitees, destroy all entries so we can save only the attendees
    @member = Member.find(params[:event_member_id.to_s])
    @event.members << @member				#insert into the join table only those members with checked boxes
		@event.update_attribute :tracked, true
		flash[:notice] = "Attendance has been tracked."
		redirect_to @event
end

  private
    def event_params
      params.require(:event).permit(:title, :date, :time, :location, :description, :invite)
    end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate
  def new
    @member = Member.new
  end

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def create
    @member = Member.new(member_params)
    if @member.save
    	# Tell the UserMailer to send a welcome email after save
      EventMailer.welcome_mail(@member).deliver!
			flash[:notice] = "Member successfully created"
      redirect_to @member
    else
      render 'new'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(member_params)
    	EventMailer.welcome_mail(@member).deliver!
			flash[:notice] = "Member successfully updated"
      redirect_to @member
    else
      render 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to members_path
  end

  private
    def member_params
      params.require(:member).permit(:uin, :first_name, :last_name, :email, :department, :designation, :paying, :status)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    $user = User.find_by_email(params[:session][:email].downcase)
    if $user && $user.authenticate(params[:session][:password])
      log_in $user
      redirect_to welcome_index_path
    else
      flash.now[:error] ='Invalid Username/Password'
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate
  def index
  end
  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
   session.delete(:user_id)
   @current_user = nil
   $user=nil
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_att.html.erb
<%= form_for @event, url: attend_path do |a| %>
  <div class="track_event_table">
    <table id="track_event">
      <tr>
	<th>Event</th>
	<td><%= @event.title %></td>
      </tr>
      <tr>
	<th>Invited Members</th>
	<td>
          <% @event.members.each do |member| %>
            <%= check_box_tag 'event_member_id[]', member.id %>
	    <%= hidden_field_tag 'event_id', @event.id %> 
            <%= member.first_name %> <%= member.last_name %><br>
          <% end %>
	</td>
      </tr>
    </table>
  </div>
  </div>
  <div class="create_button">
    <%= a.submit 'Track Attendance'%>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new_event_table">
  <table id="new_event">
    <tr>
      <th><%= f.label :title %></th>
      <td><%= f.text_field :title, placeholder: "Event Title" %></td>
    </tr>
    <tr>
      <th><%= f.label :date %></th>
      <td><%= f.text_field :date, placeholder: "YYYY-MM-DD" %></td>
    </tr>
    <tr>
      <th><%= f.label :time %></th>
      <td><%= f.text_field :time, placeholder: "HH:MM AM/PM" %></td>
    </tr>
    <tr>
      <th><%= f.label :location %></th>
      <td><%= f.text_field :location, placeholder: "Event Location" %></td>
    </tr>
    <tr>
      <th><%= f.label :description %></th>
      <td><%= f.text_area :description, placeholder: "Event Desrciption" %></td>
    </tr>
    <tr>
      <th><%= f.label :invite %></th>
      <td>
	<%= f.radio_button :invite, 'all', :checked => true %>
        <%= label :status_all, 'All Members' %>
        <%= f.radio_button :invite, 'officers' %>
        <%= label :status_officers, 'Officers Only' %>
      </td>
    </tr>    
  </table>
</div>
<div class="create_button">
	<%= f.submit %>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>
<%= button_to 'Cancel', events_path, class: "cancel_button", method: :get %>

app/views/events/index.html.erb
<h1>Events</h1>
<div class="top_buttons">
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<%= button_to 'Home', welcome_index_path, class: "page_button1", method: :get %>
<%= button_to 'New Event', new_event_path, class: "page_button2", method: :get %>
</div>
<div class="events_table">
  <table id="events">
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="4">Actions</th>
    </tr>
 
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        
        <td class="action_button"><%= button_to 'Show Details', event_path(event), class: "action_button", method: :get %></td>
	  <% if !event.tracked %>
        <td class="action_button" id="edit_button"><%= button_to 'Edit Event', edit_event_path(event), class: "action_button", method: :get %></td> <% end %>
        <td class="action_button"  id="delete_button"><%= button_to 'Delete Event', event_path(event), class: "action_button",
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
	  <% if !event.tracked %>
        <td class="action_button" id="track_button"><%= button_to 'Track Attendance', track_path(:id => event.id), class: "action_button" %></td> <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= button_to 'Cancel', events_path, class: "cancel_button", method: :get %>

app/views/events/show.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="event_table">
  <table id="event">
    <tr>
      <th>Title</th>
      <td><%= @event.title %></td>
    </tr>
    <tr>
      <th>Date</th>
      <td><%= @event.date %></td>
    </tr>
    <tr>
      <th>Time</th>
      <td><%= @event.time %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= @event.location %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @event.description %></td>
    </tr>
    <tr>
      <% if !@event.tracked %>
      <th>Invited</th>
      <% else %>
      <th>Attended</th>
      <% end %>
      <td>
        <table id="inner_table">
  				<tr>
    				<th>Last Name</th>
    				<th>First Name</th>
  				</tr>
					<% @event.members.each do |member| %>
						<tr>
   						<td><%= member.last_name %></td>
   						<td><%= member.first_name %></td>
						</tr>
					<%end %>
				</table>
      </td> 
    </tr>
  </table>
</div>
<div class="bottom_buttons">
	<% if !@event.tracked %>
		<%= button_to 'Edit', edit_event_path(@event), class: "bottom_button1", method: :get %>
	<% end %>
	<%= button_to 'Back', events_path, class: "bottom_button2", method: :get %>
</div>

app/views/events/track.html.erb
<h1>Track Event</h1>
<%= render 'att' %>
<%= button_to 'Cancel', events_path, class: "cancel_button", method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hlgsatracker</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body style="background-color: maroon;">
    <div id="hlgsalogo"/>
    </div>
    <div id="page_contents">
      <%= yield %>
    </div>

  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member do |f| %>

  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@member.errors.count, "error") %> prohibited
        this member from being saved:
      </h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new_member_table">
  <table id="new_member">
    <tr>
      <th>UIN</th>
      <td><%= f.number_field :uin, placeholder: "Last 4 digits of UIN" %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <td><%= f.text_field :first_name, placeholder: "First Name" %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= f.text_field :last_name, placeholder: "Last Name" %></td>
    </tr>
    <tr>
      <th><%= f.label :email %></th>
      <td><%= f.email_field :email, placeholder: "Email" %></td>
    </tr>
    <tr>
      <th><%= f.label :department %></th>
      <td><%= f.text_field :department, placeholder: "Department Code" %></td>
    </tr>
    <tr>
      <th><%= f.label :designation %></th>
      <td>
	<%= f.radio_button :designation, 'Member', :checked => true %>
        <%= label :designation_member, 'Member' %>
        <%= f.radio_button :designation, 'Officer' %>
        <%= label :designation_officer, 'Officer' %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :paying %></th>
      <td>
	<%= f.radio_button :paying, 'No', :checked => true %>
        <%= label :paying_no, 'No' %>
        <%= f.radio_button :paying, 'Yes' %>
        <%= label :paying_yes, 'Yes' %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :status %></th>
      <td>
	<%= f.radio_button :status, 'Student', :checked => true %>
        <%= label :status_student, 'Student' %>
        <%= f.radio_button :status, 'Graduated' %>
        <%= label :status_graduated, 'Graduated' %>
      </td>
    </tr>    
  </table>
</div>
<div class="create_button">
	<%= f.submit %>
</div>
<% end %>

app/views/members/edit.html.erb
<h1>Edit Member</h1>
<%= render 'form' %>
<%= button_to 'Cancel', members_path, class: "cancel_button", method: :get %>

app/views/members/index.html.erb
<h1>Members</h1>
<div class="top_buttons">
<%= button_to 'Home', welcome_index_path, class: "page_button1", method: :get %>
<%= button_to 'New member', new_member_path, class: "page_button2", method: :get %>
</div>
<div class="members_table">
  <table id="members">
    <tr>
      <th>UIN</th>
      <th>Last Name</th>
      <th>First Name</th>
      <th colspan="3">Actions</th>
    </tr>
 
    <% @members.each do |member| %>
      <tr>
        <td><%= member.uin %></td>
        <td><%= member.last_name %></td>
        <td><%= member.first_name %></td>
        <td class="action_button"><%= button_to 'Show Details', member_path(member), class: "action_button", method: :get %></td>
        <td class="action_button"><%= button_to 'Edit Member', edit_member_path(member), class: "action_button", method: :get %></td>
        <td class="action_button"><%= button_to 'Delete Member', member_path(member), class: "action_button",
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= button_to 'Cancel', members_path, class: "cancel_button", method: :get %>

app/views/members/show.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="member_table">
  <table id="member">
    <tr>
      <th>UIN</th>
      <td><%= @member.uin %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <td><%= @member.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @member.last_name %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @member.email %></td>
    </tr>
    <tr>
      <th>Department</th>
      <td><%= @member.department %></td>
    </tr>
    <tr>
      <th>Designation</th>
      <td><%= @member.designation %></td>
    </tr>
    <tr>
      <th>Paying</th>
      <td><%= @member.paying %></td>
    </tr>
    <tr>
      <th>Status</th>
      <td><%= @member.status %></td>
    </tr> 
    <tr>
      <th>Events</th>
      <td>
        <% @member.events.each do |event| %>
          <%= event.title %><br>
        <% end %>
      </td> 
    </tr>
  </table>
</div>
<div class="bottom_buttons">
<%= button_to 'Edit', edit_member_path(@member), class: "bottom_button1", method: :get %>
<%= button_to 'Back', members_path, class: "bottom_button2", method: :get %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/welcome/help.html.erb
<div class="top_buttons">
	<%= button_to 'Home', welcome_index_path, class: "help_page_button", method: :get %>
</div>
<div class="help_content">
<h1>How to Use HLGSA Tracker</h1>
<body>
<b>Members:</b>
<br><br>
To add a new member, click on the New Member button. This will redirect you to the form to add a new member. The format for specific fields is as follows:<br><br>
UIN: 1234 (Only the last 4 digits are allowed for security reasons.)<br>
Email: email@example.com<br>
Department: HGSA (Only the 4 letters for the department code are needed.)<br>
<br>
Proceed to Create Member and you will be redirected to the member listing or cancel to discard the form.
To permanently delete a member, click on the Delete Member button. Changes cannot be undone.
<br><br>
To edit a member, click on the corresponding member's edit button. Proceed as you did with create a member changing the necessary fields and save your changes with the Update Member button.
<br>

<br>
<b>Events:</b>
<br><br>
To add a new event, click on the New Event button. This will redirect you to the form to add a new event. The format for specific fields is
as follows:<br><br>
Date: YYYY-MM-DD
Time: HH:MM a.m./p.m.
<br><br>
Proceed to Create Event and you will be redirected to the event listing or cancel to discard the form.
To permanently delete an event, click on the Delete Event button. Changes cannot be undone.
<br><br>
To edit a event, click on the corresponding event's edit button. Proceed as you did with create an event changing the necessary fields and save your changes with the Update Event button.
<br>
To track attendance to a specific event, click on the corresponding event's track event button. This will redirect you to a page that displays all the invited members and checkboxes. Select those members who have attended the event and click Track Attendance. This will redirect you to the event page and will show a list of members who attended. Editing this event will no longer be available. 
<br>
</body>
</div>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html >
<head>
  <link rel="stylesheet" href="../../assets/stylesheets/login.css" type="text/css">
</head>
<body>
  <div class="button_card">
    <table class = "button_list">
      <tr>
	<td>
          <%= button_to 'Members', members_path, class: "members_button", method: :get %>
	</td>
	<td>
          <%= button_to 'Events', events_path, class: "events_button", method: :get %>
	</td>
      </tr>
      <tr>
	<td>      
	  <%= button_to 'Help', welcome_help_path, class: "help_button", method: :get %>
	</td>
	<td>
          <%= button_to 'Log Out', logout_path, class: "logout_button", method: :delete %>
	</td>
      </tr>    
    </table>
  </div>
</body>